### ISSUE TITLE
请问agent相关代码未来会开源吗

### ISSUE THREAD

**Issue by wwwbq** [LingmaTongyi/Codev-Bench#4]

**Comment by persistforever** [comment]
后面可能会单拉一个项目开源agent相关的内容哈

**Comment by wwwbq** [comment]
> 后面可能会单拉一个项目开源agent相关的内容哈

好的～ 非常棒的工作！

**Comment by Yaoming95** [comment]
> 后面可能会单拉一个项目开源agent相关的内容哈

作者你好，Codev-Agent在4个step中所使用的相关prompt会公开么？若公开的话有时间计划么？感谢作者
